version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: sitwise_postgres
    restart: always
    environment:
      POSTGRES_USER: sitwise_user
      POSTGRES_PASSWORD: sitwise_password
      POSTGRES_DB: sitwise_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: